### ISSUE TITLE
Added a color gradient generated from the color palette

### ISSUE THREAD

**Issue by antoninhc** [RiceCooker-dev/Lary#7]
# Problem 
Today, lary have only 10 colors defined like this :
```js
const COLOR = {
  PRIMARY: '#407AA8',
  SECONDARY: '#51ACF5',
  SUCCESS: '#8AF494',
  DANGER: '#A83B38',
  WARNING: '#F46E6A',
  INFO: '#BAA4F5',
  LIGHT: '#F3F0C7',
  DARK: '#131313',
  WHITE: '#FFFFFF',
  MUTED: '#303136'
};
```
The problem is that it is sometimes necessary to have the same color but lighter or darker.

# Expected
For each one of these colors it would take about ten variations of this one, with the color specified in the center

Example:
<img src="https://user-images.githubusercontent.com/90613106/172017997-05754bb8-99ed-42cb-b68e-175d0d53d3fb.png" width="200"/>

# Solution 

```ts
<Component backgroundColor={usePrimary(100)}/> 
<Component color={usePrimary(100)}/>
<Component borderColor={usePrimary(100)}/>
```

with a hook for this one of these color.

**Comment by LRiceCooker** [comment]
Hellow ! Done here : https://github.com/RiceCooker-dev/Lary/commit/6b1ad6bed0c234d9a3bcdb8855e8ee40f31dcbb7 

Have a nice day ;)
